### ISSUE TITLE
Cannot go get client

### ISSUE THREAD

**Issue by coffeefedora** [nats-io/nats.go#478]
I have a project that is outside of the go src folder, I am running go 1.12.5 on windows  amd64 (win10)  This is my first attempt to use NATS, not a great start!  

Getting this error:

go get github.com/nats-io/nats.go/
go: finding github.com/nats-io/nats.go v1.8.0
go: finding github.com/nats-io/nkeys v0.0.2
go: finding github.com/nats-io/nuid v1.0.1
go: finding golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
CreateFile github.com/nats-io/nats.go: The system cannot find the path specified.

**Comment by jar3b** [comment]
I have a similar issue using linux (ubuntu 18.04)

```
user@host:~/work$ go version
go version go1.12 linux/amd64
user@host:~/work$ go get github.com/nats-io/nats.go/
stat github.com/nats-io/nats.go: no such file or directory
```

Removing `~/go/pkg/mod/github.com/nats-io` folder doesn't solve the issue.

Also with vgo (import was specified as `"github.com/nats-io/nats.go"`)

```
user@host:~/work$go mod tidy
...
go: github.com/nats-io/go-nats@v1.8.0: parsing go.mod: unexpected module path "github.com/nats-io/nats.go"
go: error loading module requirements
```

**Comment by kozlovic** [comment]
I think the issue now is with nats.go and stan.go libs not modified to change the nats-server `v2` import as suggested [here](https://github.com/nats-io/nats.go/issues/477#issuecomment-498620833). I can work on that, but I am not 100% sure, so to test it means that I need to create a new tag to test the theory, which if prove wrong means I will have to delete the tag. What do you think?

**Comment by coffeefedora** [comment]
Since you are doing a rename, may I ask why nats.go if it the trailing .go means having to end it with a /?  I've never seen a go module do that, and it kinda ... smells.

Why not name it nats-client or something more indicative of what it is?  

Either way though, I am stuck which sucks because I was hoping to test nats today.  :(

**Comment by jar3b** [comment]
@kozlovic, I think this is a good idea, i can test new tag as soon as possible. In the current situation build with 1.8.0 (latest) is still impossible with default configuration.

UPD: I tried to change the imports in go tests in fork and it all worked (with nats.io, but i think stan.io fix must be similar)

**Comment by kozlovic** [comment]
@coffeefedora About the naming, it is not my decision...

**Comment by jar3b** [comment]
Issue with nats.go solved in 1.8.1, waiting for stan.go to perform a complete test.

**Comment by kozlovic** [comment]
I think I need a nats-server v2.0.0-RC19 tag first (that will have the v2 requirement), then do the stan.go change. I wonder if that's enough or if I will have to have a nats-streaming-server change too...

**Comment by coffeefedora** [comment]
i cleared my go.sum and go.mod files, and tried adding again.

this is the error:

get github.com/nats-io/nats.go/
CreateFile github.com/nats-io/nats.go: The system cannot find the path specified.

**Comment by jar3b** [comment]
@coffeefedora i working with go mod (vgo) and it works correctly, but `go get github.com/nats-io/nats.go/` still produces error. You can try `go get github.com/nats-io/nats.go/@latest`, in my case this command downloads package successfully.

**Comment by kozlovic** [comment]
@jar3b I need a v1.8.2 now because I just issued nats-server v2.0.0-RC19 that has proper go.mod with v2 requirements. If you build from docker (without any cache) then 1.8.1 will fail:
```
go: finding github.com/nats-io/nats.go v1.8.1
go: finding github.com/nats-io/nats-server/v2/server latest
go: downloading github.com/nats-io/nats.go v1.8.1
go: extracting github.com/nats-io/nats.go v1.8.1
go: finding github.com/nats-io/nats-server/v2 v2.0.0-RC8
go: downloading github.com/nats-io/nats-server/v2 v2.0.0-RC8
go: finding github.com/nats-io/nuid v1.0.1
go: finding github.com/nats-io/nkeys v0.0.2
go: finding golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
go: downloading github.com/nats-io/nkeys v0.0.2
go: downloading github.com/nats-io/nuid v1.0.1
go: extracting github.com/nats-io/nuid v1.0.1
go: extracting github.com/nats-io/nkeys v0.0.2
go: downloading golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
go: extracting golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
build test: cannot load github.com/nats-io/nats-server/v2/server: cannot find module providing package github.com/nats-io/nats-server/v2/server
```
(the test app is importing `v2` of the server. If it does not, then it would work ok.

**Comment by kozlovic** [comment]
As you see, 1.8.1 pulls RC8 that did not have go.mod modified for v2.

**Comment by kozlovic** [comment]
But this is insane.. I really don't get how this thing works...

**Comment by kozlovic** [comment]
@jar3b I have deleted the old tag of nats-server that was `v2.0.0-RC8` that ended-up be picked up as the latest because alpha sorting wise, it was indeed the last.
I think it works now for a simple nats.go/nats-server project with and without v2 import paths.

But my guess is stan.go will be more complex because of nats-streaming-server using vendor with older gnatsd v1.4.1.. I can start with updating stan.go nats-server imports, but I believe that won't be enough.

**Comment by jar3b** [comment]
With test dockerfile

```
FROM golang:1.12.5-alpine3.9 as build
RUN apk add --no-cache git gcc musl-dev
ADD . /root/go/pkg/mod/github.com/jar3b/awesomeProject
WORKDIR /root/go/pkg/mod/github.com/jar3b/awesomeProject
RUN go mod tidy && go test && go build -o app main.go

FROM alpine:3.9
WORKDIR /w
COPY --from=build /root/go/pkg/mod/github.com/jar3b/awesomeProject/app .
RUN ls -l && chmod a+x app

CMD ["./app"]
```

and go.mod

```
module github.com/jar3b/awesomeProject

go 1.12

require (
	github.com/golang/protobuf v1.3.1 // indirect
	github.com/nats-io/nats.go v1.8.1
)
```

i got (20 min ago i got RC8, for now - RC19)

```
Step 5/10 : RUN go mod tidy && go build -o app main.go
 ---> Running in f0926f4b971d
go: finding github.com/nats-io/nats-server v1.4.1
go: finding github.com/nats-io/nats-server/v2 v2.0.0-RC19
go: finding github.com/nats-io/nats.go v1.8.1
go: finding github.com/golang/protobuf v1.3.1
go: finding github.com/nats-io/gnatsd v1.4.1
go: finding github.com/nats-io/nuid v1.0.1
go: finding github.com/nats-io/nkeys v0.0.2
go: finding golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
go: finding golang.org/x/crypto v0.0.0-20190530122614-20be4c3c3ed5
go: finding github.com/nats-io/jwt v0.2.6
go: finding golang.org/x/sys v0.0.0-20190412213103-97732733099d
go: finding golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: finding golang.org/x/text v0.3.0
go: downloading github.com/nats-io/nats.go v1.8.1
go: extracting github.com/nats-io/nats.go v1.8.1
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/nats-io/nkeys v0.0.2
go: downloading github.com/nats-io/nats-server v1.4.1
go: downloading github.com/golang/protobuf v1.3.1
go: extracting github.com/nats-io/nuid v1.0.1
go: extracting github.com/nats-io/nkeys v0.0.2
go: downloading golang.org/x/crypto v0.0.0-20190530122614-20be4c3c3ed5
go: extracting github.com/nats-io/nats-server v1.4.1
go: extracting github.com/golang/protobuf v1.3.1
go: downloading github.com/nats-io/nats-server/v2 v2.0.0-RC19
go: extracting golang.org/x/crypto v0.0.0-20190530122614-20be4c3c3ed5
go: extracting github.com/nats-io/nats-server/v2 v2.0.0-RC19
go: downloading github.com/nats-io/jwt v0.2.6
go: downloading golang.org/x/sys v0.0.0-20190412213103-97732733099d
go: extracting github.com/nats-io/jwt v0.2.6
go: extracting golang.org/x/sys v0.0.0-20190412213103-97732733099d
```

I hope it's all correct now (for nats.go)

**Comment by kozlovic** [comment]
Yes, like I said, I deleted the old RC8 server tag that was being pulled as the latest. And it looks like nats.go works fine now. But I still get issues with sample app pulling streaming server/client...

**Comment by jar3b** [comment]
Yes, i can't `go mod tidy` with these imports too

```
import (
...
	"github.com/nats-io/nats.go"
	"github.com/nats-io/stan.go"
)
```
->
```
go: finding github.com/gogo/protobuf/proto latest
go: finding github.com/gogo/protobuf/gogoproto latest
go: finding github.com/nats-io/nats-streaming-server/server latest
go: finding github.com/nats-io/nats-server/test latest
go: finding github.com/hashicorp/go-msgpack/codec latest
go: finding github.com/nats-io/go-nats-streaming/pb latest
go: finding github.com/nats-io/gnatsd/server latest
go: finding github.com/nats-io/gnatsd/conf latest
go: finding github.com/nats-io/gnatsd/test latest
go: finding github.com/nats-io/gnatsd/logger latest
go: github.com/nats-io/go-nats@v1.8.1: parsing go.mod: unexpected module path "github.com/nats-io/nats.go"
go: error loading module requirements
```

**Comment by coffeefedora** [comment]
@jar3b that worked, thank you sir.

But i saw a comment above that this is not the streaming client?  both download links for nats and nats streaming go to the same github page...

**Comment by wallyqs** [comment]
@coffeefedora yes this the core NATS client, could you share where you found those links? Thanks!

**Comment by asim** [comment]
I'm now running into this

```
go: github.com/nats-io/nats.go@v1.8.1 used for two different module paths (github.com/nats-io/go-nats and github.com/nats-io/nats.go)
```

**Comment by kozlovic** [comment]
@asim Are you having that on project that pulls stan.go? I am working on updating nats-streaming-server dependencies (https://github.com/nats-io/nats-streaming-server/commit/dfa75d1c9e9361f5565952b34d9ddbb046afa094). If from my stan.go repo I do `GO111MODULE=on go get github.com/nats-io/nats-streaming-server@dfa75d1c9e9361f5565952b34d9ddbb046afa094` then the `GO111MODULE=on go test -v -p=1 ./...` I no longer get the error you reported. 
So when I pushed streaming server 0.15.0 tag, that may resolve the issue.

**Comment by asim** [comment]
I'm only making use of nats.go but I can't account for other things in the dependency graph that might rely on them. When I pin to the old version 1.7.2 everything is fine.

**Comment by kozlovic** [comment]
All, did several repos updates, so would appreciate knowing if you guys still have issues. We have NATS Server that is still v2.0.0-RC19 and need to move to v2.0.0, which means that we will need NATS Streaming to issue v0.15.1 with updated dependency.
Something that you could try if you have some error messages about go-nats is to add this in your go.mod before or after the require() section:
```
replace github.com/nats-io/go-nats => github.com/nats-io/nats.go v1.8.1
```

**Comment by asim** [comment]
The replace statements do not actually fix the issue for me and the errors persist as

```
go: github.com/nats-io/nats.go@v1.8.1 used for two different module paths (github.com/nats-io/go-nats and github.com/nats-io/nats.go)
go: github.com/nats-io/stan.go@v0.5.0 used for two different module paths (github.com/nats-io/go-nats-streaming and github.com/nats-io/stan.go)
```

**Comment by wallyqs** [comment]
Hi @asim is it possible to get a link to the `go.mod` with that result? I made a sample here (including the nats-streaming-server as well though can remove it) and `go run main.go` and `go mod tidy` are working for me: https://github.com/wallyqs/hello-nats-go-mod/blob/master/go.mod

**Comment by asim** [comment]
I believe I've resolved this. We were depending on another package which separately had stan dependencies. Please accept as resolved.

**Comment by jar3b** [comment]
Building a test app (with both stan.go and nats.go) was resolved today after `go mod tidy` with:

```
...
require (
	github.com/golang/protobuf v1.3.1 // indirect
	github.com/nats-io/nats-streaming-server v0.15.0 // indirect
	github.com/nats-io/nats.go v1.8.1
	github.com/nats-io/stan.go v0.5.0
	google.golang.org/appengine v1.6.0 // indirect
)
```

Thanks!

**Comment by kozlovic** [comment]
Glad issue is resolved for all participants in this issue. Sorry again for the troubles.

**Comment by coffeefedora** [comment]
@wallyqs 

Sorry for the delay on your question.  this is partially PEBKAC, but also a poor page layout IMO.

if you goto:  https://nats.io/download/nats-io/nats-streaming-server/

there is a large box where it says "NATS" and has nats server and clients under it.  On the right side it has the "NATS Streaming" box, and I simply missed that.  On a page that is specific to nats streaming, I am not expecting links to "nats" so prominently.  Might i recommend flipping the boxes, so the largest one is the one related to the page?

**Comment by kozlovic** [comment]
@coffeefedora With the link you posted, the top level of the page is all about NATS Streaming Server. You have the links to the github page, and all the links to download the executables directly.

At the bottom there are two boxes indeed, one for NATS Server and one for NATS Streaming. The only reason the box for NATS is bigger is because there are more clients for core NATS than streaming.

**Comment by dan-compton** [comment]
I'm not sure why this issue has been closed.  The README.md is incorrect and I encountered the same issue with go 1.12.5.  

```
usr% go get -u -v github.com/nats-io/nats.go@v1.8.1
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
get "golang.org/x/crypto": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto?go-get=1
go: finding golang.org/x/crypto latest
Fetching https://golang.org/x/sys?go-get=1
Fetching https://golang.org/x/net?go-get=1
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)
get "golang.org/x/sys": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at https://golang.org/x/sys?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
get "golang.org/x/net": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net?go-get=1
get "golang.org/x/text": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text?go-get=1
Fetching https://golang.org/x/tools?go-get=1
go: finding golang.org/x/sys latest
go: finding golang.org/x/net latest
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
get "golang.org/x/tools": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools?go-get=1
go: finding golang.org/x/tools latest
Fetching https://golang.org/x/sync?go-get=1
Parsing meta tags from https://golang.org/x/sync?go-get=1 (status code 200)
get "golang.org/x/sync": found meta tag get.metaImport{Prefix:"golang.org/x/sync", VCS:"git", RepoRoot:"https://go.googlesource.com/sync"} at https://golang.org/x/sync?go-get=1
go: finding golang.org/x/sync latest
stat github.com/nats-io/nats.go: no such file or directory
```

**Comment by wallyqs** [comment]
@dan-compton it seems that the README me workaround only

**Comment by wallyqs** [comment]
hey @dan-compton actually it works if you try this way instead, closing again:

```
GO111MODULE=on go get github.com/nats-io/nats.go/@v1.8.1/
go: downloading github.com/nats-io/nats.go v1.8.1
go: extracting github.com/nats-io/nats.go v1.8.1
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/nats-io/nkeys v0.0.2
go: extracting github.com/nats-io/nuid v1.0.1
go: extracting github.com/nats-io/nkeys v0.0.2
go: downloading golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
go: extracting golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
```

**Comment by wallyqs** [comment]
Filed in issue in `golang/go` about this: https://github.com/golang/go/issues/32483

**Comment by dcarbone** [comment]
Not that it matters, but this has effectively prevented me from using anything other than the new, and utterly horrible, "mod" concept in go.

I, personally, hate this change and the massive amounts of my time that I will now have to waste managing go.mod replace blocks in every one of my projects that is now forced to use mod by way of using nats.

**Comment by wallyqs** [comment]
@dcarbone there is also an archived version of the repository with the old name of the project that is not using modules in case it helps: https://github.com/nats-io/go-nats

**Comment by dcarbone** [comment]
actually @wallyqs it was a litany of tangentially related issues that was the primary source of my anger this morning. so i apologize for displaying it here.

`dep` is absolutely OK with the new package path, and therefore i have nothing to be upset about.

again, apologies.

**Comment by wallyqs** [comment]
@dcarbone no worries, totally understand. glad to hear you could make it work with `dep` as well 👍

**Comment by yogihardi** [comment]
hi,

i still getting error, please check below:
```
$> GO111MODULE=on go get github.com/nats-io/nats.go/@latest
$> ls $GOPATH/src/github.com/nats-io/nats.go
ls: /Users/yogi/Documents/workspaces/go-project/src/github.com/nats-io/nats.go: No such file or directory
$> go version
go version go1.13.4 darwin/amd64 
```

**Comment by kozlovic** [comment]
@yogihardi This is different. You are using go mod, so this is not going to be downloaded where you expect it to be if you were NOT using go mods. So do this instead and you should see it, along with the other nats-io deps that it may have pulled:
```
ls $GOPATH/pkg/mod/github.com/nats-io/
```

**Comment by tegk** [comment]
does not work with go mods

`go: teststand imports
	github.com/nats-io/go-nats: github.com/nats-io/go-nats@v1.8.1: parsing go.mod:
	module declares its path as: github.com/nats-io/nats.go
	        but was required as: github.com/nats-io/go-nats
`

**Comment by yogihardi** [comment]
> @yogihardi This is different. You are using go mod, so this is not going to be downloaded where you expect it to be if you were NOT using go mods. So do this instead and you should see it, along with the other nats-io deps that it may have pulled:
> 
> ```
> ls $GOPATH/pkg/mod/github.com/nats-io/
> ```

thanks @kozlovic 
my problem was failed to ran `go test` with go module, not related to `nats-io`, my apologies..

**Comment by kozlovic** [comment]
@tegk You probably have some other dependencies that still refer to go-nats instead of nats.go. If you can't update those (or ask upstream repo to do so), I believe that you may be able to locally solve by having this statement in your go.mod:
```
replace github.com/nats-io/go-nats => github.com/nats-io/nats.go v1.9.1
```
(note I use the latest version, v1.9.1, although in your error message it looks like you/they were still using v1.8.1).

**Comment by dan-compton** [comment]
Sirupsen

**Comment by kozlovic** [comment]
@dan-compton Sorry but I am not sure what you mean by "Sirupsen". Did you mean to tag someone with that GitHub handle? If so, you did not (the @ is missing)..

**Comment by bcba25** [comment]
@kozlovic dude this issue still exists until now, why cant use solve it properly ? I still getting this error no matter what I do

**Comment by wallyqs** [comment]
@bcba25 could you try with GOPROXY=direct? I think this might be solved in Go 1.14 too that is when modules became production ready

**Comment by bcba25** [comment]
@wallyqs alright will give it a try, thanks

**Comment by jextrevor** [comment]
still seeing this issue when trying to do `go get github.com/nats-io/nats.go`:
```
$ go get github.com/nats-io/nats.go

stat github.com/nats-io/nats.go: no such file or directory
```

**Comment by jextrevor** [comment]
getting the same error when using GOPROXY=direct

**Comment by jextrevor** [comment]
Was able to solve the error after running `GOPROXY=direct go mod tidy` and `GOPROXY=direct go get -u all`

**Comment by wallyqs** [comment]
@jextrevor thanks for sharing, looks there might still be some bugs in Go modules then...

**Comment by jextrevor** [comment]
still seeing this error...

**Comment by ripienaar** [comment]
What version of go do you use @jextrevor ?

**Comment by jextrevor** [comment]
I'm using 1.13.1. I'm going to upgrade to 1.14.4 and see if the issue still exists there.

**Comment by wallyqs** [comment]
Upgrading to 1.14.4 and to a newer version than (anything that matches version 1.8.1 would get this error as well) from the Go client would help with this issue.  Reason seems to be that the Go proxy has cached a version during the rename that won't go stale, skipping the proxy is another work around this issue as well.
